import type { EntitySchema } from './types';

export const muxAssetsSchema: EntitySchema = {
  properties: [
    'mux_asset_id',
    'status',
    'created_at',
    'duration',
    'max_stored_frame_rate',
    'aspect_ratio',
    'playback_ids',
    'tracks',
    'errors',
    'master_access',
    'normalize_audio',
    'static_renditions',
    'test',
    'passthrough',
    'live_stream_id',
    'ingest_type',
    'source_asset_id',
    'upload_id',
    'input_info',
    'video_quality',
    'resolution_tier',
    'non_standard_input_reasons',
    'progress',
    'meta',
    'max_resolution_tier',
    'is_live',
    'master',
    'recording_times',
  ],
} as const;
